### ISSUE TITLE
ANTLRworks fails to generate proper Java Code

### ISSUE THREAD

**Issue by FriedrichGretz** [antlr/antlrworks#5]
I have a simple grammar (cf. https://gist.github.com/4499299)

If I compile it manually with antlr-3.5-complete.jar and set up a manual test rig, everything works as expected.

However, if I use ANTLRworks 1.5, I check the grammar.. OK, I generate code.. OK I click on debug and it starts compiling and complains abour errors in the parser (cf. gist above).

**Comment by rensink** [comment]
Glad to have found this fix almost as soon as I encountered the bug; however, please note that the default download link from http://www.antlr3.org/download.html points to the broken version 1.5, not the repaired version 1.5.1. --Arend
